// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DNSProcessorClient is the client API for DNSProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DNSProcessorClient interface {
	IsEval(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type dNSProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSProcessorClient(cc grpc.ClientConnInterface) DNSProcessorClient {
	return &dNSProcessorClient{cc}
}

func (c *dNSProcessorClient) IsEval(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/DNSProcessor/IsEval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSProcessorServer is the server API for DNSProcessor service.
// All implementations must embed UnimplementedDNSProcessorServer
// for forward compatibility
type DNSProcessorServer interface {
	IsEval(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedDNSProcessorServer()
}

// UnimplementedDNSProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedDNSProcessorServer struct {
}

func (UnimplementedDNSProcessorServer) IsEval(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsEval not implemented")
}
func (UnimplementedDNSProcessorServer) mustEmbedUnimplementedDNSProcessorServer() {}

// UnsafeDNSProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSProcessorServer will
// result in compilation errors.
type UnsafeDNSProcessorServer interface {
	mustEmbedUnimplementedDNSProcessorServer()
}

func RegisterDNSProcessorServer(s grpc.ServiceRegistrar, srv DNSProcessorServer) {
	s.RegisterService(&DNSProcessor_ServiceDesc, srv)
}

func _DNSProcessor_IsEval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSProcessorServer).IsEval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DNSProcessor/IsEval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSProcessorServer).IsEval(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSProcessor_ServiceDesc is the grpc.ServiceDesc for DNSProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DNSProcessor",
	HandlerType: (*DNSProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsEval",
			Handler:    _DNSProcessor_IsEval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
